
#-----------------------------------------------------------------------
#
#   globals.properties : \uc2dc\uc2a4\ud15c
#
#-----------------------------------------------------------------------
#   1.  key = value \uad6c\uc870\uc785\ub2c8\ub2e4.
#   2.  key\uac12\uc740 \uacf5\ubc31\ubb38\uc790\ub97c \ud3ec\ud568\ubd88\uac00, value\uac12\uc740 \uacf5\ubc31\ubb38\uc790\ub97c \uac00\ub2a5
#   3.  key\uac12\uc73c\ub85c \ud55c\uae00\uc744 \uc0ac\uc6a9\ubd88\uac00,   value\uac12\uc740 \ud55c\uae00\uc0ac\uc6a9\uc774 \uac00\ub2a5
#   4.  \uc904\uc744 \ubc14\uafc0 \ud544\uc694\uac00 \uc788\uc73c\uba74 '\'\ub97c \ub77c\uc778\uc758 \ub05d\uc5d0 \ucd94\uac00(\ub9cc\uc57d  '\'\ubb38\uc790\ub97c \uc0ac\uc6a9\ud574\uc57c \ud558\ub294 \uacbd\uc6b0\ub294 '\\'\ub97c \uc0ac\uc6a9)
#   5.  Windows\uc5d0\uc11c\uc758 \ub514\ub809\ud1a0\ub9ac \ud45c\uc2dc : '\\' or '/'  ('\' \uc0ac\uc6a9\ud558\uba74 \uc548\ub428)
#   6.  Unix\uc5d0\uc11c\uc758 \ub514\ub809\ud1a0\ub9ac \ud45c\uc2dc : '/'
#   7.  \uc8fc\uc11d\ubb38 \ucc98\ub9ac\ub294  #\uc0ac\uc6a9
#   8.  value\uac12 \ub4a4\uc5d0 \uc2a4\ud398\uc774\uc2a4\uac00 \uc874\uc7ac\ud558\ub294 \uacbd\uc6b0 \uc11c\ube14\ub9bf\uc5d0\uc11c \ucc38\uc870\ud560\ub54c\ub294 \uc5d0\ub7ec\ubc1c\uc0dd\ud560 \uc218 \uc788\uc73c\ubbc0\ub85c trim()\ud558\uac70\ub098 \ub9c8\uc9c0\ub9c9 \uacf5\ubc31\uc5c6\uc774 properties \uac12\uc744 \uc124\uc815\ud560\uac83
#-----------------------------------------------------------------------


# G4C \uc5f0\uacb0\uc6a9 IP (localhost)
Globals.LocalIp = 127.0.0.1


# File Upload Settings for Tomcat 11
# \ud30c\uc77c \ud655\uc7a5\uc790 \ud654\uc774\ud2b8\ub9ac\uc2a4\ud2b8(\ud5c8\uc6a9\ubaa9\ub85d) : \ud30c\uc77c \ud655\uc7a5\uc790\ub97c (.)\uacfc \ud568\uaed8 \uc774\uc5b4\uc11c \uc0ac\uc6a9\ud558\uba70 (.)\ub85d \uc2dc\uc791\ud55c\ub2e4.
Globals.fileUpload.Extensions = .gif,.jpg,.jpeg,.png,.xls,.xlsx
Globals.fileUpload.maxFileSize = 104857600
Globals.fileUpload.maxRequestSize = 104857600
Globals.fileUpload.maxFileCount = 1000
Globals.fileUpload.fileSizeThreshold = 1048576
Globals.fileStorePath = /upload/sht

# BBS File Attach Size
Globals.posblAtchFileSize = 10485760

# File ID \uc554\ud638\ud654 \ud0a4
# \uc8fc\uc758 : \ubc18\ub4dc\uc2dc \uae30\ubcf8\uac12 "egovframe"\uc744 \ub2e4\ub978\uac83\uc73c\ub85c \ubcc0\uacbd\ud558\uc5ec \uc0ac\uc6a9\ud558\uc2dc\uae30 \ubc14\ub78d\ub2c8\ub2e4.
Globals.File.algorithmKey = egovframe

# \uc6b4\uc601\uc11c\ubc84 \ud0c0\uc785(WINDOWS, UNIX)
Globals.OsType =WINDOWS

# DB\uc11c\ubc84 \ud0c0\uc785(ORACLE, MYSQL) - datasource \ubc0f sqlMap \ud30c\uc77c \uc9c0\uc815\uc5d0 \uc0ac\uc6a9\ub428
#Globals.DbType = oracle
#Globals.DbType = tibero
Globals.DbType = cubrid
#Globals.DbType = mariadb
#Globals.DbType = mssql
#Globals.DbType = postgresql

#oracle
#Globals.DriverClassName=jDFz_u63QwyMFY6_C6nDih0uuiHPfzyhG9528I5irlI
#Globals.DriverClassName=oracle.jdbc.driver.OracleDriver
#Globals.Url=T2VDUzFIWTMiiCQqFvc7e-cn1SH8DpCGO20MOvBNgQMPy8UnJCZjM8I_jp11_GwQ
#Globals.Url=jdbc:oracle:thin:@192.168.42.119:1521:XE

#tibero
#Globals.DriverClassName=com.tmax.tibero.jdbc.TbDriver
#Globals.Url=jdbc:tibero:thin:@192.168.42.232:8629:tibero

#cubrid
Globals.DriverClassName=Eed0G5hoyn4bjmoFiMKGv-xTwWTC9DIU2d_o7vyD7og
#Globals.Url=jdbc:cubrid:49.247.4.173:33000:WIZBUILDER_RES:::?charset=utf-8
Globals.Url=HnufFtxjQpvtqn6TZ1Yn-8qOEYVi7BfdsBMXGpzGv-kLzgVvKSWVCfLTE4BPqKt-
#Globals.Url=jdbc:cubrid:49.247.5.165:33000:WIZBUILDER:::?charset=utf-8

#mariadb
#Globals.DriverClassName=shlhmtYybg6tIojM%2F8LID6lf6VjeAYDwbDngs6r2r9w%3D
#Globals.Url=jdbc:mariadb://192.168.42.236:3306/wizbuilder
#Globals.Url=wIg7pfN2lRvRDtS3vzkPrTvlUvWNA1ZDv7TJVT836IrP9vVYYGfEx%2F2T0HyeRRAp
#Globals.Url=jdbc:mariadb://49.247.5.183:3306/wizbuilder

#mssql
#Globals.DriverClassName = com.microsoft.sqlserver.jdbc.SQLServerDriver
#Globals.Url = jdbc:sqlserver://192.168.42.101:1433;DatabaseName=WIZBUILDER

#mysql
#Globals.DriverClassName=net.sf.log4jdbc.DriverSpy
#Globals.Url=jdbc:log4jdbc:mysql://192.168.42.101:3306/WIZBUILDER

#postgresql
#Globals.DriverClassName=rcwpFWlA1ovS1fDsxvjgWOsMb1Nsg%2Fx6EL6BL84YS34%3D
#Globals.Url=QQOxdoiBM9bWY5REbsp02YEKPvUOUgZLKXP3xKr5prGdNw%2FFH%2Bs0EjWvMsUkiY2WYOF8EWvKsPVIuP3DnpBD3CFr%2BbbswB4VOdNTaoIX4Uk%3D


#DB\uacc4\uc815 ID/PW\uc124\uc815
#Globals.UserName =wizbuilder_enter
Globals.UserName =LgBl3j0KRTLA4wacFaRjIg%3D%3D
Globals.Password =ssbYV%2BBlnG%2FIssu6e0szsg%3D%3D

# MainPage Setting
Globals.MainPage  =/index.do
Globals.MngrMainPage =/selectDashboardMain.do

# \ud30c\uc77c \uc5c5\ub85c\ub4dc \uacbd\ub85c(\uacbd\ub85c \uc124\uc815\uc740 \ubc18\ub4dc\uc2dc \uc808\ub300\uacbd\ub85c\ub97c \uc0ac\uc6a9\ud574\uc57c\ud568, \uacbd\ub85c \ub4a4\uc5d0 /\ub97c \ubd99\uc5ec \uc8fc\uc5b4\uc57c\ud568.)
Globals.fileStorePath   =/upload/
Globals.fileLogoPath    =/upload/logo/
Globals.filePhotoPath   =/upload/photo/
Globals.imageStorePath  =/upload/imageStore/
Globals.filePopupPath   =/upload/
Globals.mdFilePath =/upload/module/
Globals.hfmenuFilePath 	=/upload/hdftMenu/

Globals.ValidatePath =/validate/xml/

# for JFile properties 
system.uploadpath =/upload/
no.image.url =/resources/jfile/swfupload/images/no_img.gif
ftp.server.ip =127.0.0.1
ftp.user.id =test
ftp.user.password =test
    
#\ud654\uba74\ud3b8\uc9d1 \ubaa8\ub4c8 \uc124\uc815
project.initial =dggb

#\uc5c5\ub85c\ub4dc \ud5c8\uc6a9 \ud655\uc7a5\uc790
Globals.WhiteFileExt =hwp,hwpx,doc,ppt,xls,zip,pdf,txt,docx,pptx,xlsx,jpg,jpeg,gif,bmp,png,ai,psd,fla,swf,avi,wmv,wma,mpg,mpeg,mp3,wav,divx,mp4,mov,ico
Globals.WhiteImgFileExt =jpg,jpeg,gif,bmp,png,ico
Globals.WhiteExcelFileExt=xls,xlsx

# \ud30c\uc77c \ud655\uc7a5\uc790
Globals.fileExtsn.SC00000063 = jpg,jpeg,gif,bmp,png,raw,cr2,srw,nrw
Globals.fileExtsn.SC00000393 = swf,avi,wmv,mpg,mpeg,divx,mov,mkv,flv,mp4
Globals.fileExtsn.SC00000394 = wma,wmv,mp4
Globals.fileExtsn.SC00000395 = hwp,hwpx,doc,ppt,xls,txt,docx,pptx,xlsx,pdf
Globals.fileExtsn.SC00000396 = zip,egg,7z,alz,rar
Globals.fileExtsn.SC00000071 = ai,psd,fla

#URL prefix
Globals.urlPrefix=
Globals.sysMngrPrefix=/sysMngr
Globals.mngrPrefix=/mngr

Globals.cmnt.module.seq=
Globals.quit.join=
Globals.cmnt.appvlCode=
Globals.cmnt.openCode=
Globals.thumb.base.width=
Globals.prefix=

Globals.basSiteUrl=http://wiz-builder.com

Globals.qustnrExcelForm = excelTemplit/qustnrExcelForm.xlsx

Globals.siteStatExcelForm = excelTemplit/siteStatExcelForm.xlsx
Globals.visitMngrStatExcelForm = excelTemplit/visitMngrStatExcelForm.xlsx
Globals.usrMngrStatExcelForm = excelTemplit/usrMngrStatExcelForm.xlsx
Globals.cmntMngrStatExcelForm = excelTemplit/cmntMngrStatExcelForm.xlsx
Globals.menuMngrStatExcelForm = excelTemplit/menuMngrStatExcelForm.xlsx
Globals.bbsMngrStatExcelForm = excelTemplit/bbsMngrStatExcelForm.xlsx
Globals.evlScoreExcelForm = excelTemplit/evlScoreExcelForm.xlsx


#mssql
#Globals.bass.module.seq=100000003
#Globals.bbsFormUseBbsSeq=100000003,100000101
#oracle
Globals.bass.module.seq=10000000003
Globals.bbsFormUseBbsSeq=10000000003,10000000101,10000000237

Globals.usrSttusCrtfcCode=SC00000026
Globals.usrSttusQuitCode=SC00000028
Globals.usrSttusStopCode=SC00000029
Globals.bbsModuleTyCode=SC00000030
Globals.nomalModuleTyCode=SC00000031
Globals.cntntsModuleTyCode=SC00000032
Globals.schdulModuleTyCode=SC00000033
Globals.apiModuleTyCode=SC00000438


# \uc2a4\ub9c8\ud2b8\uc5d0\ub514\ud130 \uc774\ubbf8\uc9c0 \uc5c5\ub85c\ub4dc \uacbd\ub85c
#Globals.editorImageStorePath   =   /home/tmax/app/upload/smartEditor/
Globals.editorImageStorePath    =   /upload/smartEditor2.8.2.1/
#API\uc778\uc99d\ubc1b\uc744\uc218\uc788\ub294 \ucd5c\ub300\uc218 3\uac1c
Globals.API.regist.cnt=3

defaultTempltstorePath = sample/template/bootstrap/bootstrap1/

defaultTempltFolderstorePath = sample/template/bootstrap/

defaultTempltSeq = 1000000001

defaultTempltJsp = index.jsp
Globals.popupTyCode.tmplat=SC00000072

#\uc0ac\uc774\ud2b8 \ucd08\uae30 \uc0dd\uc131 \ub370\uc774\ud130
Globals.siteMenuNm = \uacf5\uc9c0\uc0ac\ud56d
Globals.siteBbsNm = \uacf5\uc9c0\uc0ac\ud56d
Globals.initSysmoduleSeq = 10000000003

#\ucd08\uae30 \uc0c1\ub2e8\uba54\ub274
Globals.siteTopMenuNmLgnY = \ub85c\uadf8\uc778:/loginForm.do,\ud68c\uc6d0\uac00\uc785:/cmm/mber/sbscrb/selectSbscrbUsrTy.do
Globals.siteTopMenuNmLgnN = \ub9c8\uc774\ud398\uc774\uc9c0:/cmm/mber/myPage/selectMyPageMain.do,\ub85c\uadf8\uc544\uc6c3:/actionLogout.do

#\ucd08\uae30 \ud558\ub2e8\uba54\ub274
Globals.siteFooterMenuNmLgnY = 
Globals.siteFooterMenuNmLgnN = 


#\ud544\uc218\uc57d\uad00\ucf54\ub4dc - \uc57d\uad00\ucf54\ub4dc
Globals.essntlStplatTyCode=SGC0000004
#\ud544\uc218\uc57d\uad00\ucf54\ub4dc - \uc57d\uad00\ucf54\ub4dc - \uac00\uc785\uc57d\uad00
#Globals.stplatTyCode.usrJoin=SC00000020
Globals.stplatTyCode.usrJoin=SC00000453
#Globals.stplatTyCode.siteStplat=SC00000021
Globals.stplatTyCode.siteStplat=SC00000454

#\uc0ac\uc6a9\uc790 \ub85c\uadf8\uc778 \ud398\uc774\uc9c0
Globals.usrLoginFormUrl=/loginForm.do

Globals.login.auth.superAdmin=10000000304
Globals.login.auth.normalAdmin=10000000307
Globals.nmbr.site.usrGroupSeq=10000000003

Globals.base.site.usrGroupSeq=10000000003
Globals.base.site.usrGroupSeq.authorSe=R

#\ube44\ubc00\ubc88\ud638\uc124\uc815\uc77c\uc790 - \ud658\uacbd\uc124\uc815\ucf54\ub4dc
Globals.updtEstbsDe.prefeCode=SGC0000038
#\ube44\ubc00\ubc88\ud638\uc124\uc815\uc77c\uc790 - \uad00\ub9ac\uc124\uc815\ucf54\ub4dc
Globals.updtEstbsDe.mngrestbsCode=SC00000308

#\uc911\ubcf5\ub85c\uadf8\uc778\uc5ec\ubd80 - \ud658\uacbd\uc124\uc815\ucf54\ub4dc
Globals.dupLogin.prefeCode=SGC0000057

#\ub85c\uadf8\uc778 \uc720\uc9c0\uc2dc\uac04 - \ud658\uacbd\uc124\uc815\ucf54\ub4dc
Globals.sessIntvl.prefeCode=SGC0000065

#\uc0ac\uc774\ud2b8\uba54\ub274\uad00\ub9ac - \uae30\ubcf8\ucee8\ud150\uce20\ud15c\ud50c\ub9bf
Globals.base.cntntsTemplatSeq =10000000036

#\uc0ac\uc774\ud2b8\uba54\ub274\uad00\ub9ac - \uae30\ubcf8\uc9c0\ub3c4\ud15c\ud50c\ub9bf
Globals.base.mapTemplatSeq =10000000126

# \uc5d1\uc140 \ud15c\ud50c\ub9bf
bbsDataBckpTemplit = excelTemplit/bbsDataBckpTemplit.xlsx
bbsCustomDataBckpTemplit = excelTemplit/bbsCustomDataBckpTemplit.xlsx
bbsSimpDataBckpTemplit = excelTemplit/bbsSimpDataBckpTemplit.xlsx
bbsMvpDataBckpTemplit = excelTemplit/bbsMvpDataBckpTemplit.xlsx
bbsLinkDataBckpTemplit = excelTemplit/bbsLinkDataBckpTemplit.xlsx
bbsFileDataBckpTemplit = excelTemplit/bbsFileDataBckpTemplit.xlsx

# AES256 \uc554\ud638\ud654 \ubaa8\ub4c8 \ud0a4
secure.aes256.key = MC45ODYwMTQ0NDcxOTk3MjIyYWJjZWRmZ2hpamtsbW4=

# \ub3c4\uba54\uc778 \uc5d1\uc140 \ub4f1\ub85d\uc2dc \uc0ac\uc6a9
# \ub3c4\uba54\uc778\uad6c\ubd84\ucf54\ub4dc
Globals.domnSeCode=SC00000001
# \uc0ac\uc6a9\uc5b8\uc5b4\ucf54\ub4dc
Globals.useLangCode=SC00000016
# \uc778\uc99d\uc124\uc815\ucf54\ub4dc
Globals.usrCrtfcPrefeCode=SGC0000037

#\ud734\ub300\ud3f0\uc778\uc99d\uc124\uc815
#NICE\ub85c\ubd80\ud130 \ubd80\uc5ec\ubc1b\uc740 \uc0ac\uc774\ud2b8 \ucf54\ub4dc
Globals.crtfc.sSiteCode=BF762
#NICE\ub85c\ubd80\ud130 \ubd80\uc5ec\ubc1b\uc740 \uc0ac\uc774\ud2b8 \ud328\uc2a4\uc6cc\ub4dc
Globals.crtfc.sSitePassword=0LOtKuBz3s0s
#\uc694\uccad \ubc88\ud638, \uc774\ub294 \uc131\uacf5/\uc2e4\ud328\ud6c4\uc5d0 \uac19\uc740 \uac12\uc73c\ub85c \ub418\ub3cc\ub824\uc8fc\uac8c \ub418\ubbc0\ub85c
Globals.crtfc.sRequestNumber=REQ0000000001 
#\uc778\uc99d\uc124\uc815\uc0ac\uc6a9\uc548\ud568
Globals.crtfc.estbs.pass=SC00000397
#\ud68c\uc6d0\ud0c8\ud1f4\ud6c4 \uc7ac\uac00\uc785 \uac00\ub2a5 \uc77c
Globals.usrReentrance.day=90
Globals.usrReCrtfc=OUT_RECRTFC

#\uba54\ub274\ubcf5\uc0ac \uc124\uc815
Globals.custom.module.seq=10000000215


#\uc5b8\uc5b4\ud329
lang.default=SC00000016
lang.SC00000016=ko
lang.SC00000019=en
lang.SC00000017=jp
lang.SC00000018=cn

mail.smtp.host=mail.wiz-wig.com
mail.smtp.port=25
mail.id=Ym1N0T7YD4bCWzvVDfSe0sOttsmrVUrKhFnYQBnqnTI
mail.passwd=Fax6V3Qib_scyOlDkLqIJw
#mail.id=noreply@wiz-wig.com
#mail.passwd=wizwig#123
mail.send.email=noreply@wiz-wig.com
mail.isSSL=false
mail.isTLS=true

reprsnt.domn.url=www.wiz-builder.co.kr
reprsnt.siteKey=wizwig

#\ud30c\uc77c\ucca8\ubd80 \uae30\ub2a5 \uc124\uc815  [ B:\uae30\ubcf8(Basic), C:\ud06c\ub85c\uc2a4\uc5c5\ub85c\ub354(Crossuploader) ]
Globals.fileEstbs=B

#\uc5d0\ub514\ud130 \uae30\ub2a5 \uc124\uc815  [ S:\uae30\ubcf8(NaverSmartEditor), C:\ub098\ubaa8\ud06c\ub85c\uc2a4\uc5d0\ub514\ud130(NamoCrossEditor) ]
Globals.editorEstbs=S


#\ubaa8\ub4c8\uc124\uc815
#\ucee8\ud150\uce20 \ucd94\uac00\uc124\uc815 \uc0ac\uc6a9\uc5ec\ubd80 [ Y:\uc0ac\uc6a9, N:\ubbf8\uc0ac\uc6a9]
Globals.cntnts.pageadi.useat=Y


#\ubd88\uac00\ud55c \uc0ac\uc774\ud2b8\ud0a4
Globals.imprty.siteKey=properties,wzwg,cmm,module,webutil,cmnt,mngr,opertntc,smartEditor2.8.2.1,stplat,siteMngr,cntnts,usr,menu,screen,subsite,sysMngr,subMngr,cntntsMngr,opnsu,usrMngr,subList,sns,clipboard,crosseditor,crossuploader,css,design,excelTemplit,font,images,jquery,js,key,license,pdf,sample,smartEditorCustom,test,upload,widesign

pass.fail.cnt=5
pass.fail.diff=5

#\uacf5\uacf5\ub370\uc774\ud130 \ud3ec\ud138 \uacf5\ud734\uc77c \uc815\ubcf4 \uc778\uc99d\ud0a4(\ub9cc\ub8cc\uc77c 2027-05-28 \uc2e0\uccad\uc790:\uc870\uc6d0\uad8c)
Globals.openApi.holidayKey=215d24cb049c3ecc0c5253bab67a9c931e1690e7a90b6c4c6ea40c0fa629df57